.TH Partitioning 1
.SH NAME
tree-inst guide to partioning an arch linux system
.SH DESCRIPTION
This page describes how you may partition drives and
mount those partitions for a function run of
.B tree-inst
.SH BIOS/MBR
You seem to be using a BIOS system and should use MBR partitioning scheme to work with
.B tree-inst
\.
.P
.B mount
,
.B partition
,
.B fdisk type
,
.B size
.P
-------------------------------------
.P
.R NONE
,
.BI /dev /sda1
,
.B 4
,
1MB
.P
.R [SWAP]
,
.BI /dev /sda2
,
.B swap
,
>512MB, If you are not sure just take half the size of the RAM installed
.P
.B /mnt
,
.BI /dev /sda3
,
.B 23
,
Remainder of the device
